//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLifeAppDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public House()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int? HouseId { get; set; }
        public string Name { get; set; }
        public string Adress { get; set; }
        public byte[] Photo { get; set; }
        public decimal State { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }

        public House(string name, string adress, byte[] photo, decimal state, string comments)
        {
            Name = name;
            Adress = adress;
            Photo = photo;
            State = state;
            Comments = comments;
            Rooms = new List<Room>();
        }
    }
}
