//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLifeAppDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Object
    {
        public int ObjectId { get; set; }
        public string Name { get; set; }
        public byte[] Photo { get; set; }
        public decimal State { get; set; }
        public string Comments { get; set; }
    }
}
